utility_frequency: 50.0             # Промышленная частота (Гц)
f_jump_max: 1.0                     # Максимальное абсолютное значение скачка частоты (Гц)
f_jump_duration_min: 5.0            # Минимальная продолжительность скачка частоты (с)
f_jump_duration_max: 50.0           # Максимальная продолжительность скачка частоты (с)
jump_probability: 0.000025          # Вероятность скачка на каждой отметке времени
simulation_time: 20                 # Длительность симуляции (с)
step: 0.00002                       # Временной шаг (с). Не может быть больше 0.00002с
U_RMS: 380                          # Действующее напряжение ДГА
phi0_min: 0                         # Минимальная начальная фаза ДГА1 (0-360) (град.)
phi0_max: 359                       # Максимальная начальная фаза ДГА1 (0-360) (град.)
f_min: 47.0                         # Нижний предел частоты ДГА1 (Гц)
f_max: 53.0                         # Верхний предел частоты ДГА1 (Гц)
RNG_seed: null                      # Порождающий элемент для ГСЧ. Целое число -> при каждом запуске скачки f1 будут одними и теми же. null -> различными (текущее системное время в качестве seed)
control: true                       # Регулировать фазовый сдвиг (true / false)
enable_fill: true                   # Вкл/откл заливку на графике (влияет на производительность)